### ISSUE TITLE
HighResolutionDateTime fails on Linux

### ISSUE THREAD

**Issue by masm22** [Abc-Arbitrage/ZeroLog#30]
Running ZeroLog on Linux throws the following exception.

```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'ZeroLog.Utils.HighResolutionDateTime' threw an exception. ---> System.DllNotFoundException: Unable to load shared library 'Kernel32.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libKernel32.dll: cannot open shared object file: No such file or directory
   at ZeroLog.Utils.HighResolutionDateTime.GetSystemTimePreciseAsFileTime(Int64& filetime)
   at ZeroLog.Utils.HighResolutionDateTime.CheckAvailability() in /_/src/ZeroLog/Utils/HighResolutionDateTime.cs:line 32
   at ZeroLog.Utils.HighResolutionDateTime..cctor() in /_/src/ZeroLog/Utils/HighResolutionDateTime.cs:line 9
   --- End of inner exception stack trace ---
   at ZeroLog.Utils.HighResolutionDateTime.get_UtcNow() in /_/src/ZeroLog/Utils/HighResolutionDateTime.cs:line 18
   at ZeroLog.Utils.SystemDateTime.get_UtcNow() in /_/src/ZeroLog/Utils/SystemDateTime.cs:line 9
   at ZeroLog.LogEvent.Initialize(Level level, Log log, LogEventArgumentExhaustionStrategy argumentExhaustionStrategy) in /_/src/ZeroLog/LogEvent.cs:line 46
   at ZeroLog.Log.CreateUnpooledLogEvent() in /_/src/ZeroLog/Log.Custom.cs:line 34
   at ZeroLog.Log..ctor(IInternalLogManager logManager, String name) in /_/src/ZeroLog/Log.Custom.cs:line 21
   at ZeroLog.LogManager.<ZeroLog.IInternalLogManager.GetLog>b__31_0(String n) in /_/src/ZeroLog/LogManager.cs:line 153
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at TestZeroLog.Program.Main(String[] args) in C:\Users\Samoussenkom\Documents\Visual Studio 2017\Projects\TestZeroLog\TestZeroLog\Program.cs:line 15
Aborted (core dumped)
root@masm-VirtualBox:/home/masm/zerolog# dotnet TestZeroLog.dll
```

This is due to incorrect exception type handled in 

```
        [DebuggerStepThrough]
        private static bool CheckAvailability()
        {
            try
            {
                GetSystemTimePreciseAsFileTime(out _);
                return true;
            }
            catch (EntryPointNotFoundException) // <-- Should be DllNotFoundException
            {
                // Not running Windows 8 or higher.
                return false;
            }
}
```

**Comment by kraikill** [comment]
@MendelMonteiro do you have plans to release this fix?

**Comment by MendelMonteiro** [comment]
@kraikill I will try to get to it today

**Comment by MendelMonteiro** [comment]
I have released a new version which includes the fix. Should be available on nuget shortly.
